### PR TITLE
A Swift rewrite

### PR DESCRIPTION
**Pull request by cc941201**
My Swift rewrite passed all unit-tests, but it has not been thoroughly tested yet.
I'm just writing it for fun. Feedback is appreciated.

### CODE REVIEW

**Comment by mxcl** [comment]
Great work! I'm happy to have this in a branch, but until Swift is ABI stable it is not responsible to add Swift to a library.

**Comment by cc941201** [comment]
Thanks. I hope to test it more before you creating a branch, especially building since I have not yet tried to build it with Swift Package Manager.

**Comment by cc941201** [comment]
I've added tag 4.0.0 and confirmed that it works on Swift Package Manager.

The committing history is a little messy though. Do I squash them into one commit or split the giant rewrite commit?

**Comment by nathanhosselton** [comment]
@cc941201 Hey! I've created the [swift-rewrite branch](https://github.com/mxcl/OMGHTTPURLRQ/tree/swift-rewrite) for this for the time being. Perhaps once Swift is nice and stable we can merge it in. Thanks for your [huge] contribution!

**Comment by mxcl** [comment]
May I suggest making a separate project? There are people that would want this, for sure. And I would be happy to switch this project to Swift once Swift is ABI stable. Until then there are cons with a library being Swift for sure.

**Comment by cc941201** [comment]
I won’t be able to contribute to open source since I’ll be joining CFNetwork next year, but I can push for API improvements from within.

If anyone wants to take over, you can build on top of my rewrite or rewrite it again since mine is so outdated. It would be nice if features like `Codable` are adopted.

**Pull request closed without merging**
