### PR TITLE
tvOS support (part 2)

### PR DESCRIPTION
**Pull request by bruceflowers**
This PR is a continuation of https://github.com/mxcl/OMGHTTPURLRQ/pull/10

### CODE REVIEW

**Comment by mxcl** [comment]
You committed `bruceflowers.xcuserdatad`

**Comment by bruceflowers** [comment]
removed xcuserdata...

**Comment by bruceflowers** [comment]
bump

**Comment by mxcl** [comment]
Please merge @nathanhosselton

**Pull request merged**
