### PR TITLE
adds tvOS support

### PR DESCRIPTION
**Pull request by bruceflowers**
Rebased against your master branch. 

I recognize this will require developers to use Xcode 7.1, so just let me know if you've got different ideas about where this might want to go.

### CODE REVIEW

**Comment by mxcl** [comment]
We'll need to put this in a separate branch until Xcode 7.1 is live. I suggest `tvOS` as the name.

**Comment by bruceflowers** [comment]
tvOS sounds fine. I don't think I have permissions to create a branch - if you make one, I'll be happy to point a PR at it.

**Comment by nathanhosselton** [comment]
@bruceflowers You can fork and create a new branch then PR. Then we will merge.

**Comment by mxcl** [comment]
Or…… We can just merge using the command line to any branch we like.

**Comment by bruceflowers** [comment]
Closing this one, opening https://github.com/mxcl/OMGHTTPURLRQ/pull/11 as requested by @nathanhosselton

**Pull request closed without merging**
